spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-01.cxwuk4ak66st.ap-northeast-2.rds.amazonaws.com:3306/test?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: tnals024064
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update